<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<AssemblyTitle>Folder Icon Changer</AssemblyTitle>
		<AssemblyName>Folder Icon Changer</AssemblyName>
		<RootNamespace>FolderIconChangerWPF</RootNamespace>

		<TargetFramework>net10.0-windows</TargetFramework>
		<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
		<!--<TargetFrameworks>net9.0-windows;net472</TargetFrameworks>-->
		<UseWPF>true</UseWPF>
		<!--<UseWindowsForms>true</UseWindowsForms>-->
		<!--<AutoGenerateBindingRedirects Condition="$(TargetFramework.StartsWith('net4')) Or $(TargetFramework.StartsWith('net3'))">true</AutoGenerateBindingRedirects>-->
		<AutoGenerateBindingRedirects Condition="$(TargetFramework.StartsWith('net4')) Or $(TargetFramework.StartsWith('net3'))">true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
		<Product>Folder Icon Changer</Product>
		<NeutralLanguage>en</NeutralLanguage>
		<Description>easy-to-use &amp; fast way to change folder's icon</Description>
		<Copyright>Copyright ©  2019-2026</Copyright>
		<Version>4.2.3.0</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<FileVersion>$(Version)</FileVersion>
		<ProductVersion>$(Version)</ProductVersion>

		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<GenerateAssemblyVersionAttribute>true</GenerateAssemblyVersionAttribute>
		<GenerateAssemblyFileVersionAttribute>true</GenerateAssemblyFileVersionAttribute>
		<GenerateAssemblyInformationalVersionAttribute>true</GenerateAssemblyInformationalVersionAttribute>
		<!--<GenerateAssemblyInfo>false</GenerateAssemblyInfo>-->

		<Company>Ezz Hassan</Company>
		<Authors>Ezz Hassan</Authors>
		<Platforms>AnyCPU;x86;x64</Platforms>
		<!--Workaround for Error	MSB4216	Could not run the "GenerateResource" -->
		<!--<GenerateResourceMSBuildArchitecture>CurrentArchitecture</GenerateResourceMSBuildArchitecture>-->
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugType>full</DebugType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
		<DebugType>full</DebugType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
		<DebugType>full</DebugType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<DebugType>pdbonly</DebugType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
		<DebugType>pdbonly</DebugType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup>
		<StartupObject>FolderIconChangerWPF.App</StartupObject>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationIcon>Resources\icon.ico</ApplicationIcon>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<Win32Resource />
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<Resource Include="Fonts\fontawesome-webfont.ttf" />
		<Resource Include="Fonts\Lato-Bold.ttf" />
		<Resource Include="Fonts\Lato-Regular.ttf" />
		<Resource Include="Fonts\Lato-Thin.ttf" />
	</ItemGroup>


	<ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
		<Reference Include="System" />
		<Reference Include="System.Data" />
		<Reference Include="System.Drawing" />
		<Reference Include="System.Xml" />
		<Reference Include="Microsoft.CSharp" />
		<Reference Include="System.Core" />
		<Reference Include="System.Xml.Linq" />
		<Reference Include="System.Data.DataSetExtensions" />
		<Reference Include="System.Net.Http" />
		<Reference Include="System.Xaml">
			<RequiredTargetFramework>4.0</RequiredTargetFramework>
		</Reference>
		<Reference Include="WindowsBase" />
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
	</ItemGroup>

	<!--References for .Net Core-->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net4'))==False">
		<PackageReference Include="Microsoft.Windows.Compatibility" Version="10.0.11" />
	</ItemGroup>

	<!--PackageReference for all framworks-->
	<ItemGroup>
		<PackageReference Include="MahApps.Metro" Version="2.4.11" />
		<!--<PackageReference Include="MahApps.Metro.Resources" Version="0.6.1" />-->
		<!--<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />-->
		<!--<PackageReference Include="Microsoft.Windows.Compatibility" Version="3.1.0" />-->
		<!--<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />-->
		<!--<PackageReference Include="System.Net.Http" Version="4.3.4" />-->
		<!--<PackageReference Include="Microsoft.Windows.Shell" Version="3.0.1" />-->
		<!--<PackageReference Include="MvvmLightLibs" Version="5.4.1.1" />-->
		<PackageReference Include="PortableJsonSettingsProvider" Version="0.2.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<!--<PackageReference Include="WPFLocalizeExtension" Version="3.10.0" />-->
		<PackageReference Include="WPFLocalizeExtensionEzzFork" Version="3.10.1" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="icon.ico" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Resources\icon.ico" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Images\Ezz14_Left.jpg" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Ezz_Helper\Other Helpers\" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>


</Project>
