//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderIconChangerWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderIconChangerWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string AppDark {
            get {
                return ResourceManager.GetString("AppDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Theme.
        /// </summary>
        public static string AppDarkBlue {
            get {
                return ResourceManager.GetString("AppDarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy-to-use and fast way to change folder&apos;s icon.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string AppLight {
            get {
                return ResourceManager.GetString("AppLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Recent Files.
        /// </summary>
        public static string bClearRecentFiles {
            get {
                return ResourceManager.GetString("bClearRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Recent Folders.
        /// </summary>
        public static string bClearRecentFolders {
            get {
                return ResourceManager.GetString("bClearRecentFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for an icon file.
        /// </summary>
        public static string BrowseForAnIconFile {
            get {
                return ResourceManager.GetString("BrowseForAnIconFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Ezz Hasan.
        /// </summary>
        public static string ByEzhassen {
            get {
                return ResourceManager.GetString("ByEzhassen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;{0}&apos; button to get the icon first..
        /// </summary>
        public static string ClickGetIconButtonToGetTheIconFirst {
            get {
                return ResourceManager.GetString("ClickGetIconButtonToGetTheIconFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy new icon to the target folder.
        /// </summary>
        public static string CopyIconToFolder {
            get {
                return ResourceManager.GetString("CopyIconToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Icon wont be copied to the target folder.
        /// </summary>
        public static string CopyIconToFolderOff {
            get {
                return ResourceManager.GetString("CopyIconToFolderOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Icon will be copied to the target folder.
        /// </summary>
        public static string CopyIconToFolderOn {
            get {
                return ResourceManager.GetString("CopyIconToFolderOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Icon.
        /// </summary>
        public static string CurrentIcon {
            get {
                return ResourceManager.GetString("CurrentIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezz Hasan.
        /// </summary>
        public static string DevName {
            get {
                return ResourceManager.GetString("DevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done :).
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Exists!.
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Images Group.
        /// </summary>
        public static string FormIcomGroupTitle {
            get {
                return ResourceManager.GetString("FormIcomGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string FormOptionsTitle {
            get {
                return ResourceManager.GetString("FormOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Best Icon Fit.
        /// </summary>
        public static string GenerateBestFit {
            get {
                return ResourceManager.GetString("GenerateBestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new Icon from an image.
        /// </summary>
        public static string GenerateNewIconFromAnImage {
            get {
                return ResourceManager.GetString("GenerateNewIconFromAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Folder Icon.
        /// </summary>
        public static string GetFolderIcon {
            get {
                return ResourceManager.GetString("GetFolderIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Icon.
        /// </summary>
        public static string GetIcon {
            get {
                return ResourceManager.GetString("GetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the Icon file if it exists in the target folder.
        /// </summary>
        public static string HideIcon {
            get {
                return ResourceManager.GetString("HideIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Icon file wont be hidden.
        /// </summary>
        public static string HideIconOff {
            get {
                return ResourceManager.GetString("HideIconOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Icon file will be hidden If it exists in the target folder.
        /// </summary>
        public static string HideIconOn {
            get {
                return ResourceManager.GetString("HideIconOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon from image.
        /// </summary>
        public static string IconFromImage {
            get {
                return ResourceManager.GetString("IconFromImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP.
        /// </summary>
        public static string IconImageFormat_BMP {
            get {
                return ResourceManager.GetString("IconImageFormat_BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG.
        /// </summary>
        public static string IconImageFormat_PNG {
            get {
                return ResourceManager.GetString("IconImageFormat_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        public static string IconImageFormat_UNKNOWN {
            get {
                return ResourceManager.GetString("IconImageFormat_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 IndexedColors.
        /// </summary>
        public static string ImageColorsTypes__16_IndexedColors {
            get {
                return ResourceManager.GetString("ImageColorsTypes__16_IndexedColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256 IndexedColors.
        /// </summary>
        public static string ImageColorsTypes__256_IndexedColors {
            get {
                return ResourceManager.GetString("ImageColorsTypes__256_IndexedColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Channel.
        /// </summary>
        public static string ImageColorsTypes_Alpha_Channel {
            get {
                return ResourceManager.GetString("ImageColorsTypes_Alpha_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome.
        /// </summary>
        public static string ImageColorsTypes_Monochrome {
            get {
                return ResourceManager.GetString("ImageColorsTypes_Monochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Colors.
        /// </summary>
        public static string ImageColorsTypes_True_Colors {
            get {
                return ResourceManager.GetString("ImageColorsTypes_True_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ImageColorsTypes_Unknown {
            get {
                return ResourceManager.GetString("ImageColorsTypes_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAASrklEQVR4nOWbe5RdVX3HP7+99zn3MZOZTIbMhCAhPGMCBAiPCKJWBJ8gD7Xa1a7WZYuCoq22vpbLF1Vql9XS2lqttkutfaxl8VVTFFERQVioIBASHsnkPZN5ZJ537j33PPavf5x7J3duJiGgIWh/a5179t5n33PO77f37/f7/n57H/h/TtJ2biUFzDP4LkeKPAvzB6DtAtDGuZ1xZWFq9vML/OdIUuvz/CH6tTPeLox5Amgd8XaGD8Zcs59wcCEdCWp93sFGF+YLR9rahIYAhDapcOgZ8GxXi4WYbm2f19asGOZP/0Mx/GwUxpMx3dreqgZeXvyC95KkKgpGvQcVFSMGnZsKqpIzalrvnYtJW5rMPNG0W5WDtHsRupNJjq3vbhw76chmUTnIzNYDGGvcVefdV8GDylxd1Ssg1grGeIyRcvdi78Kwh3IpUDEmM8YRBA4R8dYIxuZcCmTa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LangFlagBase64 {
            get {
                return ResourceManager.GetString("LangFlagBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Icon Changer.
        /// </summary>
        public static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MainWindowMenu {
            get {
                return ResourceManager.GetString("MainWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will try to Generate Best Fit Icon By generating multiple icons with deferent sizes.
        ///
        ///Continue?.
        /// </summary>
        public static string msgGenBestFit {
            get {
                return ResourceManager.GetString("msgGenBestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Icon.
        /// </summary>
        public static string NewIcon {
            get {
                return ResourceManager.GetString("NewIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Icon Info.
        /// </summary>
        public static string NewIconInfo {
            get {
                return ResourceManager.GetString("NewIconInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder.
        /// </summary>
        public static string OpenContainingFolder {
            get {
                return ResourceManager.GetString("OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in explorer.
        /// </summary>
        public static string OpenFolderInExplorer {
            get {
                return ResourceManager.GetString("OpenFolderInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Options.
        /// </summary>
        public static string OtherOptions {
            get {
                return ResourceManager.GetString("OtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default icon.
        /// </summary>
        public static string ResetToDefaultIcon {
            get {
                return ResourceManager.GetString("ResetToDefaultIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ResetToDefaultIconMsg {
            get {
                return ResourceManager.GetString("ResetToDefaultIconMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Select_Icon_Abort {
            get {
                return ResourceManager.GetString("Select_Icon_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported formats.
        /// </summary>
        public static string Select_Icon_AllSupportedFormats {
            get {
                return ResourceManager.GetString("Select_Icon_AllSupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Select_Icon_Back {
            get {
                return ResourceManager.GetString("Select_Icon_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Select_Icon_Cancel {
            get {
                return ResourceManager.GetString("Select_Icon_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Select_Icon_Count {
            get {
                return ResourceManager.GetString("Select_Icon_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Text.
        /// </summary>
        public static string Select_Icon_DrawText {
            get {
                return ResourceManager.GetString("Select_Icon_DrawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Icon.
        /// </summary>
        public static string Select_Icon_ExportIcon {
            get {
                return ResourceManager.GetString("Select_Icon_ExportIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Image.
        /// </summary>
        public static string Select_Icon_ExportImage {
            get {
                return ResourceManager.GetString("Select_Icon_ExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Icons.
        /// </summary>
        public static string Select_Icon_GetIcons {
            get {
                return ResourceManager.GetString("Select_Icon_GetIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Select_Icon_Index {
            get {
                return ResourceManager.GetString("Select_Icon_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any icon to be shown!.
        /// </summary>
        public static string Select_Icon_NoIconToShow {
            get {
                return ResourceManager.GetString("Select_Icon_NoIconToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Select_Icon_OK {
            get {
                return ResourceManager.GetString("Select_Icon_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Select_Icon_Refresh {
            get {
                return ResourceManager.GetString("Select_Icon_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as ....
        /// </summary>
        public static string Select_Icon_SaveAs {
            get {
                return ResourceManager.GetString("Select_Icon_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select_Icon_Select {
            get {
                return ResourceManager.GetString("Select_Icon_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected count.
        /// </summary>
        public static string Select_Icon_SelectedCount {
            get {
                return ResourceManager.GetString("Select_Icon_SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon group.
        /// </summary>
        public static string Select_Icon_ShowIconGroup {
            get {
                return ResourceManager.GetString("Select_Icon_ShowIconGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretched Image.
        /// </summary>
        public static string Select_Icon_StretchedImage {
            get {
                return ResourceManager.GetString("Select_Icon_StretchedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Small Images Too.
        /// </summary>
        public static string Select_Icon_StretchedSmallImagesToo {
            get {
                return ResourceManager.GetString("Select_Icon_StretchedSmallImagesToo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Icon.
        /// </summary>
        public static string Select_Icon_Title {
            get {
                return ResourceManager.GetString("Select_Icon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Select_Icon_View {
            get {
                return ResourceManager.GetString("Select_Icon_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any Image/Picture to be converted to ico format with sizes (p256, p128, p64, p48, p32, p16) and the Color is Alpha_Channel (32bit).
        /// </summary>
        public static string SelectAnyImageToBeConverted {
            get {
                return ResourceManager.GetString("SelectAnyImageToBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target Folder.
        /// </summary>
        public static string SelectTargetFolder {
            get {
                return ResourceManager.GetString("SelectTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the new generated icon?.
        /// </summary>
        public static string SelectToSaveNewGeneratedIcon {
            get {
                return ResourceManager.GetString("SelectToSaveNewGeneratedIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Current Folder when creating Icon From Image.
        /// </summary>
        public static string ShowCurrentFolderForIconFromImage {
            get {
                return ResourceManager.GetString("ShowCurrentFolderForIconFromImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon group.
        /// </summary>
        public static string ShowIconGroup {
            get {
                return ResourceManager.GetString("ShowIconGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder;Icon;Changer.
        /// </summary>
        public static string SplitedTitle {
            get {
                return ResourceManager.GetString("SplitedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        public static string tAppName {
            get {
                return ResourceManager.GetString("tAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder.
        /// </summary>
        public static string TargetFolder {
            get {
                return ResourceManager.GetString("TargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string tCopyright {
            get {
                return ResourceManager.GetString("tCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string tDescription {
            get {
                return ResourceManager.GetString("tDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Name.
        /// </summary>
        public static string tDevName {
            get {
                return ResourceManager.GetString("tDevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error!.
        /// </summary>
        public static string ThereIsAnError {
            get {
                return ResourceManager.GetString("ThereIsAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay On Top.
        /// </summary>
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        public static string VersionMiniText {
            get {
                return ResourceManager.GetString("VersionMiniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string WindowCloseToolTip {
            get {
                return ResourceManager.GetString("WindowCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string WindowMaximizeToolTip {
            get {
                return ResourceManager.GetString("WindowMaximizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string WindowMinimizeToolTip {
            get {
                return ResourceManager.GetString("WindowMinimizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string WindowRestoreToolTip {
            get {
                return ResourceManager.GetString("WindowRestoreToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
